import 'annotation.dart';
import 'aws_data.dart';
import 'cause.dart';
import 'http_data.dart';
import '../utils.dart';

/// A nested span within a [Segment].
///
/// Subsegments are immutable value objects; every mutation returns a new copy.
final class Subsegment {
  Subsegment._({
    required this.id,
    required this.name,
    required this.namespace,
    required this.startTime,
    required this.inProgress,
    this.endTime,
    this.fault = false,
    this.error = false,
    this.throttle = false,
    this.cause,
    this.http,
    this.aws,
    this.annotations,
    this.metadata,
    this.subsegments = const [],
  });

  final String id;
  final String name;
  final String namespace;
  final double startTime;
  final double? endTime;
  final bool inProgress;
  final bool fault;
  final bool error;
  final bool throttle;
  final Cause? cause;
  final HttpData? http;
  final AwsData? aws;
  final Map<String, Object>? annotations;
  // X-Ray schema: {"namespace": {"key": value}}
  final Map<String, Map<String, Object>>? metadata;
  final List<Subsegment> subsegments;

  factory Subsegment.begin({
    required String name,
    String namespace = 'local',
  }) =>
      Subsegment._(
        id: randomHex(16),
        name: name,
        namespace: namespace,
        startTime: nowSeconds(),
        inProgress: true,
      );

  /// Builds an open subsegment with an explicit [id] and [startTime].
  ///
  /// **Internal / tracer-only.** Used by the tracer's scope machinery to
  /// materialize a subsegment that was accumulated at runtime — its id and start
  /// time were fixed when the scope opened, so they cannot be regenerated by
  /// [Subsegment.begin]. Application code should not call this; use
  /// [Subsegment.begin] or the tracer's `captureAsync` instead.
  factory Subsegment.open({
    required String id,
    required String name,
    required String namespace,
    required double startTime,
  }) =>
      Subsegment._(
        id: id,
        name: name,
        namespace: namespace,
        startTime: startTime,
        inProgress: true,
      );

  /// Returns a closed copy with [endTime] set.
  Subsegment close() {
    if (endTime != null) return this;
    return _copyWith(endTime: nowSeconds(), inProgress: false);
  }

  Subsegment withFault([Object? err]) => _copyWith(
        fault: true,
        cause:
            err != null ? Cause(exceptions: [XRayException.from(err)]) : cause,
      );

  Subsegment withError([Object? err]) => _copyWith(
        error: true,
        cause:
            err != null ? Cause(exceptions: [XRayException.from(err)]) : cause,
      );

  Subsegment withThrottle() => _copyWith(throttle: true, error: true);

  /// Attaches an error [cause] (the AWS exception type/message), without
  /// otherwise changing the fault/error/throttle flags — use when the flags
  /// were already set from the HTTP status via [applyStatus].
  Subsegment withCause(Cause cause) => _copyWith(cause: cause);

  Subsegment withHttp(HttpData data) => _copyWith(http: data);

  /// Records the request/response of an HTTP call and applies the
  /// fault/error/throttle flags implied by [status]. Shared by the HTTP and
  /// AWS-client instrumentation paths.
  Subsegment withHttpCall({
    required String method,
    required String url,
    required int status,
    int? contentLength,
    bool traced = false,
  }) =>
      _withHttpStatusCause(status).withHttp(HttpData(
        request: HttpRequestData(
          method: method,
          url: url,
          traced: traced ? true : null,
        ),
        response:
            HttpResponseData(status: status, contentLength: contentLength),
      ));

  Subsegment withAws(AwsData data) => _copyWith(aws: data);

  Subsegment addChild(Subsegment child) =>
      _copyWith(subsegments: [...subsegments, child]);

  /// Adds an indexed annotation.
  ///
  /// [key] is sanitized to X-Ray's allowed character set (`[A-Za-z0-9_]`) and
  /// [value] is coerced to a scalar if it is not already one — see
  /// `sanitizeAnnotationKey` / `coerceAnnotationValue`.
  Subsegment annotate(String key, Object value) => _copyWith(
        annotations: {
          ...?annotations,
          sanitizeAnnotationKey(key): coerceAnnotationValue(value),
        },
      );

  /// Adds non-indexed metadata under [namespace] (default `'default'`).
  ///
  /// Metadata is not validated: [value] may be any JSON-serializable object.
  /// Avoid the `AWS.` namespace prefix, which X-Ray reserves for its own use.
  Subsegment addMetadata(
    String key,
    Object value, {
    String namespace = 'default',
  }) {
    final updated = <String, Map<String, Object>>{...?metadata};
    updated[namespace] = {...?updated[namespace], key: value};
    return _copyWith(metadata: updated);
  }

  /// Applies fault/error/throttle flags based on an HTTP status code.
  Subsegment applyStatus(int statusCode) {
    if (statusCode == 429) return withThrottle();
    if (statusCode >= 500) return withFault();
    if (statusCode >= 400) return withError();
    return this;
  }

  Subsegment _withHttpStatusCause(int statusCode) {
    final flagged = applyStatus(statusCode);
    if (statusCode < 400 || flagged.cause != null) return flagged;
    return flagged.withCause(Cause(exceptions: [
      XRayException(
        id: randomHex(16),
        type: 'HTTP $statusCode',
        message: 'Downstream HTTP response returned status $statusCode',
        remote: true,
      ),
    ]));
  }

  Map<String, Object?> toJson() => {
        'id': id,
        'name': name,
        'namespace': namespace,
        'start_time': startTime,
        if (endTime != null) 'end_time': endTime,
        if (inProgress) 'in_progress': true,
        if (fault) 'fault': true,
        if (error) 'error': true,
        if (throttle) 'throttle': true,
        if (cause != null) 'cause': cause!.toJson(),
        if (http != null) 'http': http!.toJson(),
        if (aws != null) 'aws': aws!.toJson(),
        if (annotations != null) 'annotations': annotations,
        if (metadata != null) 'metadata': metadata,
        if (subsegments.isNotEmpty)
          'subsegments': [for (final s in subsegments) s.toJson()],
      };

  Subsegment _copyWith({
    double? endTime,
    bool? inProgress,
    bool? fault,
    bool? error,
    bool? throttle,
    Cause? cause,
    HttpData? http,
    AwsData? aws,
    Map<String, Object>? annotations,
    Map<String, Map<String, Object>>? metadata,
    List<Subsegment>? subsegments,
  }) =>
      Subsegment._(
        id: id,
        name: name,
        namespace: namespace,
        startTime: startTime,
        endTime: endTime ?? this.endTime,
        inProgress: inProgress ?? this.inProgress,
        fault: fault ?? this.fault,
        error: error ?? this.error,
        throttle: throttle ?? this.throttle,
        cause: cause ?? this.cause,
        http: http ?? this.http,
        aws: aws ?? this.aws,
        annotations: annotations ?? this.annotations,
        metadata: metadata ?? this.metadata,
        subsegments: subsegments ?? this.subsegments,
      );
}
